approve_by_comment: true
approve_regex: '^(Approved|:shipit:|:\+1:|\+1|Code Certified)'
reject_regex: '^(Rejected|:shipit:|:\-1:|\-1|Needs developer)'
reset_on_push: false
reviewers:
  name: UTRS Architects
  members:
  - 'tool-developers'
  name: default
  required: 1
